"""
Free RSS feeds and geo-hub lookup database.
All sources here are publicly accessible without any API key.
"""

# ── RSS Feeds ─────────────────────────────────────────────────────────────────
# Format: (label, url, tier)
#   tier 1 = wire services / official
#   tier 2 = major outlets
#   tier 3 = specialist / regional
RSS_FEEDS = [
    # ── Tier 1: Wire services (conflict/world focus only) ──────────────────────
    ("AP News – World",           "https://feeds.apnews.com/rss/apf-intlnews",                    1),
    ("Reuters – World",           "https://feeds.reuters.com/reuters/worldNews",                   1),
    ("Reuters – Defence",         "https://feeds.reuters.com/reuters/USdefense",                   1),
    ("AFP via Google",            "https://news.google.com/rss/search?q=AFP+conflict+military&hl=en", 1),

    # ── Tier 2: Mission-aligned broadcast/international outlets ───────────────
    ("BBC – Middle East",         "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml",      2),
    ("BBC – Asia",                "https://feeds.bbci.co.uk/news/world/asia/rss.xml",             2),
    ("BBC – Africa",              "https://feeds.bbci.co.uk/news/world/africa/rss.xml",           2),
    ("BBC – Europe",              "https://feeds.bbci.co.uk/news/world/europe/rss.xml",           2),
    ("Al Jazeera – All",          "https://www.aljazeera.com/xml/rss/all.xml",                    2),
    ("Radio Free Europe",         "https://www.rferl.org/api/zpqpmopipe",                         2),
    ("VOA – News",                "https://www.voanews.com/api/zmgqepumqs",                       2),
    ("VOA – Africa",              "https://www.voanews.com/api/zqqoiuyppe",                       2),
    ("VOA – Asia",                "https://www.voanews.com/api/zrmpiypmqs",                       2),
    ("VOA – Russia",              "https://www.voanews.com/api/zrvoqyuiqs",                       2),

    # ── Tier 2: Additional world & Asia-Pacific (upgrade plan) ─────────────────
    ("NPR – News",                "https://feeds.npr.org/1004/rss.xml",                           2),
    ("BBC – World",               "http://feeds.bbci.co.uk/news/world/rss.xml",                   2),
    ("NYT – World",               "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",       2),
    ("GDACS – Global disasters",    "https://www.gdacs.org/xml/rss.xml",                            2),
    ("NHK World",                 "https://www3.nhk.or.jp/nhkworld/rss/world.xml",                2),
    ("Channel News Asia",         "https://www.channelnewsasia.com/rssfeed/8395986",              2),

    # ── Tier 3: Defense & military ────────────────────────────────────────────
    ("Defense News",              "https://www.defensenews.com/arc/outboundfeeds/rss/",          3),
    ("Breaking Defense",          "https://breakingdefense.com/feed/",                            3),
    ("The War Zone",              "https://www.thedrive.com/the-war-zone/rss",                    3),
    ("Jane's (free)",             "https://www.janes.com/feeds/news",                             3),
    ("Military Times",            "https://www.militarytimes.com/arc/outboundfeeds/rss/category/news/", 3),
    ("USNI News",                 "https://news.usni.org/feed",                                   3),
    ("Naval News",                "https://www.navalnews.com/feed/",                              3),

    # ── Tier 3: Geopolitics & conflict analysis ───────────────────────────────
    ("ISW – Ukraine/Russia",      "https://www.understandingwar.org/rss.xml",                     3),
    ("ISW – Middle East",         "https://www.understandingwar.org/rss.xml",                     3),
    ("Bellingcat",                "https://www.bellingcat.com/feed/",                             3),
    ("War on the Rocks",          "https://warontherocks.com/feed/",                              3),
    ("Foreign Policy",            "https://foreignpolicy.com/feed/",                              3),
    ("Council on Foreign Relations", "https://www.cfr.org/rss.xml",                              3),
    ("RAND – News",               "https://www.rand.org/news/press.xml",                          3),
    ("Carnegie Endowment",        "https://carnegieendowment.org/rss/solr.xml",                   3),
    ("Int'l Crisis Group",        "https://www.crisisgroup.org/rss.xml",                          3),
    ("Airwars",                   "https://airwars.org/feed/",                                    3),
    ("SIPRI – News",              "https://www.sipri.org/rss.xml",                                3),
    ("Open Nuclear Network",      "https://opennuclear.org/feed/",                               3),

    # ── Tier 3: Regional — conflict-zone specialist outlets ───────────────────
    ("Kyiv Independent",          "https://kyivindependent.com/feed/",                            3),
    ("Jerusalem Post",            "https://www.jpost.com/Rss/RssFeedsHeadlines.aspx",             3),
    ("Middle East Eye",           "https://www.middleeasteye.net/rss",                            3),
    ("Arab News",                 "https://www.arabnews.com/rss.xml",                             3),
    ("South China Morning Post",  "https://www.scmp.com/rss/91/feed",                             3),
    ("Nikkei Asia – Politics",    "https://asia.nikkei.com/rss/feed/section/politics",            3),
    ("Nikkei Asia – RSS",         "https://asia.nikkei.com/rss",                                  3),
    ("Dawn – Pakistan",           "https://www.dawn.com/feeds/home",                              3),
    ("Latin America – Reuters",   "https://feeds.reuters.com/reuters/latinamericaNews",            3),
    ("MercoPress",                "https://en.mercopress.com/rss/",                               3),
    ("Focus Taiwan",              "https://focustaiwan.tw/rss",                                   3),
    ("Kyodo News",                "https://english.kyodonews.net/rss/news.xml",                     3),
    ("The Diplomat",              "https://thediplomat.com/feed/",                                3),
    ("Stars and Stripes – Pacific", "https://www.stripes.com/feeds/pacific.rss",                  3),
    ("Yonhap News",               "https://en.yna.co.kr/RSS/news.xml",                             3),
    ("Taipei Times",              "https://www.taipeitimes.com/xml/pda.rss",                      3),
    ("Asia Times",                "https://asiatimes.com/feed/",                                  3),
    ("Japan Times",               "https://www.japantimes.co.jp/feed/",                           3),

    # ── Tier 3: Energy & strategic infrastructure ──────────────────────────────
    ("Oil Price",                 "https://oilprice.com/rss/main",                                3),
    ("Energy Monitor",            "https://www.energymonitor.ai/feed/",                           3),

    # ── Tier 3: Nation-state cyber / threat intelligence ──────────────────────
    # Replaced consumer-focused blogs with proper threat-intel sources
    ("Recorded Future – Blog",    "https://www.recordedfuture.com/feed",                          3),
    ("CISA Alerts",               "https://www.cisa.gov/cybersecurity-advisories/all.xml",        3),
    ("Mandiant – Blog",           "https://www.mandiant.com/resources/blog/rss.xml",              3),
    ("Xinhua News Agency", "http://www.xinhuanet.com/english/rss/worldrss.xml", 2),
    ("People's Daily", "http://en.people.cn/rss/90777.xml", 2),
    ("Global Times", "https://www.globaltimes.cn/rss/outbrain.xml", 2),
    ("China Daily", "http://www.chinadaily.com.cn/rss/china_rss.xml", 2),
    ("CGTN (China Global Television Network)", "https://www.cgtn.com/subscribe/rss/section/world.xml", 2),
    ("China Internet Information Center (China.org.cn)", "http://www.china.org.cn/xml/node_7247699.xml", 2),
    ("Ministry of Foreign Affairs of the PRC", "https://www.fmprc.gov.cn/eng/rss.xml", 2),
    ("State Council of the PRC", "http://english.www.gov.cn/rss/news.xml", 2),
    ("TASS News Agency", "http://tass.com/rss/v2.xml", 2),
    ("RT (Russia Today)", "https://www.rt.com/rss/", 2),
    ("Sputnik News", "https://sputnikglobe.com/export/rss2/archive/index.xml", 2),
    ("RIA Novosti", "https://ria.ru/export/rss2/archive/index.xml", 2),
    ("Izvestia", "https://iz.ru/xml/rss/all.xml", 2),
    ("Rossiyskaya Gazeta", "https://rg.ru/xml/index.xml", 2),
    ("VGTRK (Rossiya TV)", "https://russia.tv/rss/news/", 2),
    ("Interfax Russia", "https://www.interfax.ru/rss.asp", 2),
    ("President of Russia (Kremlin)", "http://kremlin.ru/events/president/news/feed", 2),
    ("Ministry of Foreign Affairs of Russia", "https://www.mid.ru/en/maps/rss/", 2),
    ("IRNA (Islamic Republic News Agency)", "https://en.irna.ir/rss.xml", 2),
    ("Press TV", "https://www.presstv.ir/rss.xml", 2),
    ("Tasnim News Agency", "https://www.tasnimnews.com/en/rss", 2),
    ("Fars News Agency", "https://en.farsnews.ir/rss.aspx", 2),
    ("Mehr News Agency", "https://en.mehrnews.com/rss", 2),
    ("IRIB News (Islamic Republic of Iran Broadcasting)", "https://www.iribnews.ir/en/rss", 2),
    ("Tehran Times", "https://www.tehrantimes.com/rss", 2),
    ("Financial Tribune", "https://financialtribune.com/rss.xml", 2),
    ("Office of the Supreme Leader (Khamenei.ir)", "https://english.khamenei.ir/rss/news.xml", 2),
    ("President of Iran", "https://president.ir/en/rss", 2),
    ("Ministry of Foreign Affairs of Iran", "https://en.mfa.ir/rss.xml", 2),
    ("KCNA (Korean Central News Agency)", "https://kcnawatch.org/kcna-rss-feed/", 2),
    ("Al Mayadeen", "https://english.almayadeen.net/rss.xml", 2),
    ("Al Manar TV", "https://www.almanar.com.lb/rss.xml", 2),
    ("TeleSUR", "https://www.telesurenglish.net/rss/", 2),
    ("Granma", "http://www.granma.cu/idiomas/ingles/rss.xml", 2),
    ("Prensa Latina", "https://www.plenglish.com/rss.xml", 2),
    ("BelTA", "https://eng.belta.by/rss/", 2),
    ("SANA", "https://sana.sy/en/?feed=rss2", 2),
    ("UN News", "https://news.un.org/feed/subscribe/en/news/all/rss.xml", 2),
    ("IAEA", "https://www.iaea.org/feeds/topstories.xml", 2),
    ("OCHA / ReliefWeb", "https://reliefweb.int/updates/rss.xml", 2),
    ("Anadolu Agency", "https://www.aa.com.tr/en/rss/default?cat=world", 2),
    ("Saudi Press Agency", "https://www.spa.gov.sa/rss/en", 2),
    ("AllAfrica", "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", 2),
    ("African Arguments", "https://africanarguments.org/feed/", 2),
    ("The Africa Report", "https://www.theafricareport.com/feed/", 2),
    ("ISS Africa (Institute for Security Studies)", "https://issafrica.org/rss.xml", 2),
    ("ACLED (Armed Conflict Location & Event Data)", "https://acleddata.com/feed/", 2),
    ("Relief Web Africa", "https://reliefweb.int/country/rss.xml?primary_country=Africa", 2),
    ("ECOWAS News", "https://www.ecowas.int/feed/", 2),
    ("African Union", "https://au.int/en/rss.xml", 2),
    ("IRIN News (humanitarian/conflict)", "https://www.thenewhumanitarian.org/rss.xml", 2),
    ("Sahel Research Group", "https://sahelresearch.africa.ufl.edu/feed/", 2),
    ("Jihadology", "https://jihadology.net/feed/", 2),
    ("SITE Intelligence Group", "https://cts.siteintelgroup.com/rss.xml", 2),
    ("MEMRI Jihad & Terrorism", "https://www.memri.org/rss/memrijttm.xml", 2),
    ("Jamestown Terrorism Monitor", "https://jamestown.org/programs/tm/feed/", 2),
    ("START (National Consortium for the Study of Terrorism)", "https://www.start.umd.edu/rss.xml", 2),
    ("RAND Terrorism Research", "https://www.rand.org/topics/terrorism-and-homeland-security.xml", 2),
    ("Combating Terrorism Center (West Point)", "https://ctc.westpoint.edu/feed/", 2),
    ("Global Terrorism Database Updates", "https://www.start.umd.edu/gtd/rss.xml", 2),
    ("Foreign Policy Research Institute", "https://www.fpri.org/feed/", 2),
    ("Lawfare (national security/terrorism law)", "https://www.lawfaremedia.org/feed", 2),
    ("ACLED Conflict Data", "https://acleddata.com/feed/", 2),
    ("Long War Journal", "https://www.longwarjournal.org/feed", 2),
    ("Soufan Center", "https://thesoufancenter.org/feed/", 2),
    ("IntelCenter", "https://intelcenter.com/rss/ic-rss.xml", 2),
    ("Yemen Monitor", "https://www.yemenmonitor.com/feed/", 2),
    ("Yemen News Agency (SABA, Houthi-controlled)", "https://www.sabanews.net/en/rss.xml", 2),
    ("Marib Press", "https://marebpress.net/rss.xml", 2),
    ("Al Masdar Online", "https://almasdaronline.com/rss.xml", 2),
    ("Yemen Future", "https://yemenfuture.net/feed/", 2),
    ("Al Ayyam (southern Yemen)", "https://www.alayyam.info/rss.xml", 2),
    ("ACLED Yemen", "https://acleddata.com/feed/", 2),
    ("UN OCHA Yemen", "https://www.unocha.org/yemen/rss.xml", 2),
    ("Armed Conflict Survey Yemen", "https://www.iiss.org/rss/", 2),
    ("Tolo News", "https://tolonews.com/rss.xml", 2),
    ("Ariana News", "https://www.ariananews.af/feed/", 2),
    ("Pajhwok Afghan News", "https://pajhwok.com/feed/", 2),
    ("Khaama Press", "https://www.khaama.com/feed/", 2),
    ("Afghanistan Analysts Network", "https://www.afghanistan-analysts.org/feed/", 2),
    ("Radio Free Europe / Radio Liberty Afghanistan", "https://www.rferl.org/api/zrqoimveir", 2),
    ("UN OCHA Afghanistan", "https://www.unocha.org/afghanistan/rss.xml", 2),
    ("ACLED Afghanistan", "https://acleddata.com/feed/", 2),
    ("Long War Journal Afghanistan", "https://www.longwarjournal.org/archives/afghanistan/feed", 2),
    ("Relief Web Afghanistan", "https://reliefweb.int/updates/rss.xml?primary_country=3", 2),
    ("Irrawaddy", "https://www.irrawaddy.com/feed", 2),
    ("Myanmar Now", "https://myanmar-now.org/en/feed/", 2),
    ("Mizzima News", "https://mizzima.com/rss.xml", 2),
    ("DVB (Democratic Voice of Burma)", "https://english.dvb.no/feed/", 2),
    ("AAPP (Political Prisoner Monitoring)", "https://aappb.org/feed/", 2),
    ("UN OCHA Myanmar", "https://www.unocha.org/myanmar/rss.xml", 2),
    ("The Hindu", "https://www.thehindu.com/feeder/default.rss", 2),
    ("Times of India", "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", 2),
    ("Geo News Pakistan", "https://www.geo.tv/rss/1", 2),
    ("The Print (India security focus)", "https://theprint.in/feed/", 2),
    ("NDTV", "https://feeds.feedburner.com/ndtvnews-top-stories", 2),

    # ── Tier 2–3: Additional world / defense / maritime (Mar 2026) ───────────
    ("Defense News – Global", "https://www.defensenews.com/arc/outboundfeeds/rss/category/global/?outputType=xml", 3),
    ("US War Department News", "https://www.war.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=1&Site=945", 2),
    ("North Korea Times", "https://feeds.northkoreatimes.com/rss/08aysdf7tga9s7f7", 3),
    ("News24 – World", "https://feeds.news24.com/articles/news24/World/rss", 2),
    ("News24 – Top Stories", "https://feeds.capi24.com/v1/Search/articles/news24/TopStories/rss", 2),
    ("News24 – World (CAPI)", "https://feeds.capi24.com/v1/Search/articles/news24/World/rss", 2),
    ("MarineLink News", "https://www.marinelink.com/news/rss", 3),
    ("CBS News – World", "https://www.cbsnews.com/latest/rss/world", 2),
    ("Reddit – r/worldnews (top)", "https://www.reddit.com/r/worldnews/top/.rss", 3),
    ("France 24 – EN RSS", "https://www.france24.com/en/rss", 2),
    ("Firstpost – World", "https://www.firstpost.com/commonfeeds/v1/mfp/rss/world.xml", 2),
    ("CNA Taiwan – Politics", "https://feeds.feedburner.com/rsscna/politics", 2),
    ("CNA Taiwan – International", "https://feeds.feedburner.com/rsscna/intworld", 2),
    ("CNA Taiwan – Cross-strait", "https://feeds.feedburner.com/rsscna/mainland", 2),
]

# ── Strategic geo-hubs for headline → lat/lon mapping ─────────────────────────
# Ordered by specificity: more specific entries first so they win over generic ones.
GEO_HUBS = [
    # Active conflict zones (high priority)
    {"name": "Gaza",         "lat": 31.50, "lon": 34.46, "priority": 10,
     "keywords": ["gaza", "rafah", "khan younis", "hamas", "west bank", "palestin"]},
    {"name": "Ukraine",      "lat": 50.45, "lon": 30.52, "priority": 10,
     "keywords": ["ukraine", "kyiv", "kharkiv", "kherson", "zaporizhzhia", "mariupol", "dnipro", "odessa", "bakhmut", "frontline"]},
    {"name": "Sudan",        "lat": 15.55, "lon": 32.53, "priority": 9,
     "keywords": ["sudan", "khartoum", "rsf", "darfur", "omdurman"]},
    {"name": "Yemen",        "lat": 15.36, "lon": 44.19, "priority": 9,
     "keywords": ["yemen", "sanaa", "sana'a", "houthi", "aden", "hudaydah"]},
    {"name": "Myanmar",      "lat": 19.74, "lon": 96.07, "priority": 9,
     "keywords": ["myanmar", "burma", "rangoon", "yangon", "mandalay", "tatmadaw"]},
    {"name": "Afghanistan",  "lat": 34.52, "lon": 69.17, "priority": 9,
     "keywords": ["afghanistan", "kabul", "taliban", "kandahar"]},
    {"name": "Haiti",        "lat": 18.54, "lon": -72.33, "priority": 9,
     "keywords": ["haiti", "port-au-prince", "gang", "haitian"]},
    {"name": "Congo (DRC)",  "lat": -4.32, "lon": 15.32, "priority": 9,
     "keywords": ["congo", "drc", "kinshasa", "goma", "m23", "bukavu"]},
    {"name": "Mali/Sahel",   "lat": 14.0,  "lon": -3.0,  "priority": 8,
     "keywords": ["mali", "sahel", "bamako", "burkina faso", "niger", "ouagadougou", "niamey"]},
    {"name": "Somalia",      "lat": 2.04,  "lon": 45.34, "priority": 8,
     "keywords": ["somalia", "mogadishu", "al-shabaab", "al shabaab"]},
    {"name": "Ethiopia",     "lat": 9.02,  "lon": 38.74, "priority": 8,
     "keywords": ["ethiopia", "addis ababa", "tigray", "amhara", "oromia"]},
    {"name": "Syria",        "lat": 34.80, "lon": 38.99, "priority": 8,
     "keywords": ["syria", "damascus", "aleppo", "idlib", "deir ez-zor", "syrian"]},

    # Strategic actors
    {"name": "Russia",       "lat": 55.75, "lon": 37.61, "priority": 7,
     "keywords": ["russia", "moscow", "kremlin", "putin", "russian", "st. petersburg"]},
    {"name": "Iran",         "lat": 35.69, "lon": 51.38, "priority": 7,
     "keywords": ["iran", "tehran", "irgc", "khamenei", "iranian", "isfahan"]},
    {"name": "Israel",       "lat": 31.77, "lon": 35.21, "priority": 7,
     "keywords": ["israel", "tel aviv", "netanyahu", "idf", "jerusalem", "israeli"]},
    {"name": "North Korea",  "lat": 39.03, "lon": 125.75, "priority": 7,
     "keywords": ["north korea", "kim jong", "pyongyang", "dprk", "icbm"]},
    {"name": "China",        "lat": 39.90, "lon": 116.39, "priority": 6,
     "keywords": ["china", "beijing", "xi jinping", "chinese", "pla", "shanghai"]},
    {"name": "Taiwan",       "lat": 25.03, "lon": 121.56, "priority": 7,
     "keywords": ["taiwan", "taipei", "taiwan strait", "pla taiwan"]},
    {"name": "Pakistan",     "lat": 33.72, "lon": 73.06, "priority": 6,
     "keywords": ["pakistan", "islamabad", "karachi", "lahore", "isi"]},
    {"name": "Lebanon",      "lat": 33.88, "lon": 35.49, "priority": 7,
     "keywords": ["lebanon", "beirut", "hezbollah", "lebanese"]},
    {"name": "Iraq",         "lat": 33.32, "lon": 44.36, "priority": 6,
     "keywords": ["iraq", "baghdad", "mosul", "basra", "iraqi"]},
    {"name": "Turkey",       "lat": 39.92, "lon": 32.85, "priority": 5,
     "keywords": ["turkey", "ankara", "erdogan", "turkish", "istanbul"]},
    {"name": "Venezuela",    "lat": 10.48, "lon": -66.87, "priority": 6,
     "keywords": ["venezuela", "caracas", "maduro", "venezuelan"]},

    # Strategic waterways
    {"name": "Red Sea",      "lat": 20.0,  "lon": 38.5,  "priority": 8,
     "keywords": ["red sea", "bab al-mandab", "bab-el-mandeb"]},
    {"name": "Suez Canal",   "lat": 30.5,  "lon": 32.3,  "priority": 8,
     "keywords": ["suez", "suez canal"]},
    {"name": "Strait of Hormuz", "lat": 26.5, "lon": 56.3, "priority": 8,
     "keywords": ["strait of hormuz", "hormuz", "persian gulf"]},
    {"name": "South China Sea", "lat": 14.0, "lon": 114.0, "priority": 7,
     "keywords": ["south china sea", "spratly", "paracel", "scarborough"]},
    {"name": "Taiwan Strait","lat": 24.5,  "lon": 119.5, "priority": 8,
     "keywords": ["taiwan strait", "strait of taiwan"]},
    {"name": "Black Sea",    "lat": 43.0,  "lon": 33.0,  "priority": 7,
     "keywords": ["black sea", "kerch strait", "kerch bridge"]},

    # Institutions / regions (lower priority)
    {"name": "NATO/Europe",  "lat": 50.84, "lon": 4.35,  "priority": 3,
     "keywords": ["nato", "brussels", "european union", "eu summit", "europe"]},
    {"name": "United States","lat": 38.89, "lon": -77.03,"priority": 3,
     "keywords": ["united states", "washington", "pentagon", "white house", "congress", "u.s."]},
    {"name": "United Nations","lat": 40.74, "lon": -73.97,"priority": 4,
     "keywords": ["united nations", "un security council", "unsc", "un general assembly"]},
    {"name": "India",        "lat": 28.61, "lon": 77.21, "priority": 4,
     "keywords": ["india", "new delhi", "kashmir", "modi", "indian"]},
    {"name": "Arctic",       "lat": 79.0,  "lon": 15.0,  "priority": 5,
     "keywords": ["arctic", "svalbard", "greenland", "north pole"]},
]

# ── Country instability baselines (0–100) ─────────────────────────────────────
# These are approximate structural-fragility baselines.
COUNTRY_RISK = {
    "Afghanistan":  {"risk": 91, "lat": 33.93, "lon": 67.70, "iso": "AF"},
    "Gaza/Palestine":{"risk": 95, "lat": 31.35, "lon": 34.30, "iso": "PS"},
    "Yemen":        {"risk": 90, "lat": 15.55, "lon": 48.51, "iso": "YE"},
    "Sudan":        {"risk": 86, "lat": 12.86, "lon": 30.21, "iso": "SD"},
    "Myanmar":      {"risk": 82, "lat": 21.91, "lon": 95.95, "iso": "MM"},
    "Syria":        {"risk": 82, "lat": 34.80, "lon": 38.99, "iso": "SY"},
    "South Sudan":  {"risk": 81, "lat": 6.87,  "lon": 31.30, "iso": "SS"},
    "Somalia":      {"risk": 83, "lat": 5.15,  "lon": 46.19, "iso": "SO"},
    "Congo (DRC)":  {"risk": 79, "lat": -4.03, "lon": 21.75, "iso": "CD"},
    "Haiti":        {"risk": 80, "lat": 18.97, "lon": -72.28, "iso": "HT"},
    "Ukraine":      {"risk": 88, "lat": 48.37, "lon": 31.16, "iso": "UA"},
    "Libya":        {"risk": 73, "lat": 26.33, "lon": 17.22, "iso": "LY"},
    "Mali":         {"risk": 75, "lat": 17.57, "lon": -3.99, "iso": "ML"},
    "Burkina Faso": {"risk": 72, "lat": 12.36, "lon": -1.53, "iso": "BF"},
    "Niger":        {"risk": 71, "lat": 17.60, "lon": 8.08,  "iso": "NE"},
    "Ethiopia":     {"risk": 69, "lat": 9.14,  "lon": 40.48, "iso": "ET"},
    "Lebanon":      {"risk": 76, "lat": 33.85, "lon": 35.86, "iso": "LB"},
    "North Korea":  {"risk": 75, "lat": 40.33, "lon": 127.51,"iso": "KP"},
    "Iraq":         {"risk": 67, "lat": 33.22, "lon": 43.67, "iso": "IQ"},
    "Iran":         {"risk": 66, "lat": 32.42, "lon": 53.68, "iso": "IR"},
    "Pakistan":     {"risk": 63, "lat": 30.37, "lon": 69.34, "iso": "PK"},
    "Venezuela":    {"risk": 61, "lat": 6.42,  "lon": -66.58,"iso": "VE"},
    "Taiwan":       {"risk": 58, "lat": 23.69, "lon": 120.96,"iso": "TW"},
    "Mozambique":   {"risk": 59, "lat": -18.66,"lon": 35.52, "iso": "MZ"},
    "Russia":       {"risk": 72, "lat": 61.52, "lon": 105.31,"iso": "RU"},
    "China":        {"risk": 36, "lat": 35.86, "lon": 104.19,"iso": "CN"},
    "Turkey":       {"risk": 49, "lat": 38.96, "lon": 35.24, "iso": "TR"},
    "Israel":       {"risk": 78, "lat": 31.04, "lon": 34.85, "iso": "IL"},
}

# ── RSShub Telegram → RSS bridges (free, no API key) ─────────────────────────
# rsshub.app converts public Telegram channels to RSS. No registration needed.
# These are all public OSINT / conflict-monitoring channels.
RSSHUB_FEEDS = [
    ("[TG] Intel Slava",     "https://rsshub.app/telegram/channel/intelslava",      1),
    ("[TG] OSINT Defender",  "https://rsshub.app/telegram/channel/osintdefender",    1),
    ("[TG] Ukraine Now",     "https://rsshub.app/telegram/channel/UkraineNow",       2),
    ("[TG] Clash Report",    "https://rsshub.app/telegram/channel/ClashReport",      2),
    ("[TG] Military Summary","https://rsshub.app/telegram/channel/militarysummary",  2),
    ("[TG] war_monitor",     "https://rsshub.app/telegram/channel/war_monitor",      2),
    ("[TG] Bellum Acta News","https://rsshub.app/telegram/channel/BellumActaNews",   2),
    ("[TG] Geopolitics Prime","https://rsshub.app/telegram/channel/geopolitics_prime", 2),
    ("[TG] GeneralMCNews",   "https://rsshub.app/telegram/channel/GeneralMCNews",    2),
    ("[TG] English Abu Ali", "https://rsshub.app/telegram/channel/englishabuali",    2),
    ("[TG] rybar_in_english", "https://rsshub.app/telegram/channel/rybar_in_english", 2),
    ("[TG] noel_reports", "https://rsshub.app/telegram/channel/noel_reports", 2),
    ("[TG] AMK_Mapping", "https://rsshub.app/telegram/channel/AMK_Mapping", 2),
    ("[TG] itarmyofukraine2022", "https://rsshub.app/telegram/channel/itarmyofukraine2022", 2),
    ("[TG] mod_russia_en", "https://rsshub.app/telegram/channel/mod_russia_en", 2),
    ("[TG] news_kremlin_eng", "https://rsshub.app/telegram/channel/news_kremlin_eng", 2),
    ("[TG] liveukraine_media", "https://rsshub.app/telegram/channel/liveukraine_media", 2),
    ("[TG] beholdisraelchannel", "https://rsshub.app/telegram/channel/beholdisraelchannel", 2),
    ("[TG] slavyangrad", "https://rsshub.app/telegram/channel/slavyangrad", 2),
    ("[TG] DDGeopolitics", "https://rsshub.app/telegram/channel/DDGeopolitics", 2),
    ("[TG] eurasianchoice", "https://rsshub.app/telegram/channel/eurasianchoice", 2),
    ("[TG] thediplomatmagazine", "https://rsshub.app/telegram/channel/thediplomatmagazine", 2),
    ("[TG] bioclandestine", "https://rsshub.app/telegram/channel/bioclandestine", 2),
    ("[TG] OsintDefender", "https://rsshub.app/telegram/channel/OsintDefender", 2),
    ("[TG] TerrorAlarm", "https://rsshub.app/telegram/channel/TerrorAlarm", 2),
    ("[TG] MilitantWire", "https://rsshub.app/telegram/channel/MilitantWire", 2),
    ("[TG] ThePrintIndia", "https://rsshub.app/telegram/channel/ThePrintIndia", 2),
    ("[TG] Observer Research Foundation", "https://rsshub.app/telegram/channel/orftg", 2),
    ("[TG] Republic TV Live News", "https://rsshub.app/telegram/channel/RepublicLive", 2),
    ("[TG] DIU Ukraine (HUR)", "https://rsshub.app/telegram/channel/DIUkraine", 2),
    ("[TG] Our Wars, Today", "https://rsshub.app/telegram/channel/ourwarstoday", 2),
    ("[TG] Stratkom ZSU (AFU)", "https://rsshub.app/telegram/channel/AFUStratCom", 2),
    ("[TG] Astra", "https://rsshub.app/telegram/channel/astrapress", 2),
    ("[TG] Rybar", "https://rsshub.app/telegram/channel/rybar", 2),
    ("[TG] WarGonzo", "https://rsshub.app/telegram/channel/wargonzo", 2),
    ("[TG] Readovka", "https://rsshub.app/telegram/channel/readovkanews", 2),
    ("[TG] MoD Russia", "https://rsshub.app/telegram/channel/mod_russia", 2),
    ("[TG] CSTO (ODKB)", "https://rsshub.app/telegram/channel/ODKB_CSTO", 2),
    ("[TG] Ukraine MFA", "https://rsshub.app/telegram/channel/Ukraine_MFA", 2),
    ("[TG] The New York Times", "https://rsshub.app/telegram/channel/nytimes", 2),
    ("[TG] UNIAN", "https://rsshub.app/telegram/channel/uniannet", 2),
    ("[TG] Starshe Eddy", "https://rsshub.app/telegram/channel/vysokygovorit", 2),
    ("[TG] NEWSWORLD_23", "https://rsshub.app/telegram/channel/NEWSWORLD_23", 2),
    ("[TG] Pravda Gerashchenko", "https://rsshub.app/telegram/channel/Pravda_Gerashchenko", 2),
    ("[TG] Vitaly Kim / Mykolaiv ODA", "https://rsshub.app/telegram/channel/mykolaivskaODA", 2),
    ("[TG] Nikolayevsky Vanyok", "https://rsshub.app/telegram/channel/vanek_nikolaev", 2),
    ("[TG] Nexta Live", "https://rsshub.app/telegram/channel/nexta_live", 2),
    ("[TG] Milinfolive", "https://rsshub.app/telegram/channel/milinfolive", 2),
    ("[TG] Doninside", "https://rsshub.app/telegram/channel/doninside", 2),
    ("[TG] SolovievLive", "https://rsshub.app/telegram/channel/SolovievLive", 2),
    ("[TG] Strana.ua", "https://rsshub.app/telegram/channel/stranaua", 2),
    ("[TG] bne IntelliNews", "https://rsshub.app/telegram/channel/bneintellinews", 2),
]

# ── Broadcast streams (free internet radio, no API key) ──────────────────────
# format: "mp3" for direct audio, "hls" for M3U8/HLS streams (needs hls.js in browser)
BROADCAST_STREAMS = [
    {
        "id": "bbc_ws",
        "name": "BBC World Service",
        "url": "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service",
        "format": "mp3",
        "lang": "EN",
        "org": "BBC",
        "desc": "24/7 international news & analysis",
    },
    {
        "id": "voa_en",
        "name": "VOA News Radio",
        "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/VOA_NEWS_RADIO.mp3",
        "format": "mp3",
        "lang": "EN",
        "org": "VOA",
        "desc": "Voice of America — live English news",
    },
    {
        "id": "dw_en",
        "name": "DW Radio English",
        "url": "https://radio.dw.com/dw/mp3/live_english.mp3",
        "format": "mp3",
        "lang": "EN",
        "org": "DW",
        "desc": "Deutsche Welle international service",
    },
    {
        "id": "rfi_en",
        "name": "RFI English",
        "url": "https://live02.rfi.fr/rfimonde-96k.mp3",
        "format": "mp3",
        "lang": "EN",
        "org": "RFI",
        "desc": "Radio France Internationale",
    },
    {
        "id": "rfe_rl",
        "name": "Radio Free Europe",
        "url": "https://audio.rferl.org/eng/rferl_en.mp3",
        "format": "mp3",
        "lang": "EN",
        "org": "RFERL",
        "desc": "News & programming into restricted regions",
    },
    {
        "id": "un_radio",
        "name": "UN Radio English",
        "url": "https://audio.un.org/un-radio/en/live/aac.m3u8",
        "format": "hls",
        "lang": "EN",
        "org": "UN",
        "desc": "Official United Nations news radio",
    },
    {
        "id": "france24_en",
        "name": "France 24 (EN)",
        "url": "https://stream.france24.com/hls/live/2037218/F24_EN_LO_HLS/master.m3u8",
        "format": "hls",
        "lang": "EN",
        "org": "France24",
        "desc": "France 24 English international channel",
    },
]

# ── Public live feeds / cameras (no API key required) ─────────────────────────
# type "youtube_ch": embed current live stream for a YouTube channel ID
# type "youtube_v" : specific persistent YouTube video ID (24/7 streams)
# type "iframe"    : direct embeddable URL (must allow iframing)
PUBLIC_CAMERAS = [
    # ── News live streams (global coverage, YouTube channel embeds) ──
    {
        "id": "aljazeera", "name": "Al Jazeera Live",
        "city": "GLOBAL", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCNye-wNBqNL5ZzHSJj3l8Bg",
        "lat": 25.28, "lon": 51.53,
        "desc": "Al Jazeera English 24/7 live",
    },
    {
        "id": "france24", "name": "France 24 Live",
        "city": "PARIS", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCQfwfsi5VrQ8yKZ-UWmAEFg",
        "lat": 48.85, "lon": 2.35,
        "desc": "France 24 English international news",
    },
    {
        "id": "dwnews", "name": "DW News Live",
        "city": "BERLIN", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCknLrEdhRCp1aegoMqRaCZg",
        "lat": 52.52, "lon": 13.40,
        "desc": "Deutsche Welle live news",
    },
    {
        "id": "skynews", "name": "Sky News Live",
        "city": "LONDON", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCoMdktPbSTixAyNGwb-UYkQ",
        "lat": 51.50, "lon": -0.12,
        "desc": "Sky News 24/7 live",
    },
    {
        "id": "nhkworld", "name": "NHK World Live",
        "city": "TOKYO", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCiivmO71RErA5iJgM9-X6aA",
        "lat": 35.68, "lon": 139.69,
        "desc": "NHK World Japan live coverage",
    },
    {
        "id": "wion", "name": "WION Live",
        "city": "NEW DELHI", "region": "NEWS",
        "type": "youtube_ch", "embed_id": "UCVxjl9rmtfWXGAXN8-R3A0g",
        "lat": 28.61, "lon": 77.21,
        "desc": "India-based global news channel",
    },
    # ── City live webcams (YouTube-hosted 24/7 city cams) ──
    {
        "id": "earthtv_nyc", "name": "Times Square NYC",
        "city": "NEW YORK", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCm8_eMPuuNGFjfxdpNJpWXg",
        "lat": 40.75, "lon": -73.98,
        "desc": "24/7 live street cam — Times Square",
    },
    {
        "id": "earthtv_hk", "name": "Hong Kong Skyline",
        "city": "HONG KONG", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCkXmLjEr95LVtGuIm3l2dPg",
        "lat": 22.30, "lon": 114.16,
        "desc": "Live panoramic city cam",
    },
    {
        "id": "earthtv_dc", "name": "Washington DC Mall",
        "city": "WASHINGTON DC", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCHKyqLF1ELxRFOcBMEH-KgA",
        "lat": 38.89, "lon": -77.03,
        "desc": "National Mall area live cam",
    },
    {
        "id": "livecam_istanbul", "name": "Istanbul Bosphorus",
        "city": "ISTANBUL", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCL5nqHTJwlnpJV0hc_RcGhw",
        "lat": 41.01, "lon": 28.97,
        "desc": "Bosphorus Strait live cam",
    },
    {
        "id": "earthtv_dubai", "name": "Dubai Skyline",
        "city": "DUBAI", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCa-_HyUjVkVqfL8P2vBMBxw",
        "lat": 25.20, "lon": 55.27,
        "desc": "Live Dubai city panorama",
    },
    {
        "id": "livecam_taipei", "name": "Taipei City",
        "city": "TAIPEI", "region": "URBAN",
        "type": "youtube_ch", "embed_id": "UCxgAuX5XoNAN3dv2mBGB0mQ",
        "lat": 25.03, "lon": 121.56,
        "desc": "Live Taipei city feed — Taiwan Strait watch",
    },
]